// registry/vue/components/dialog/dialog-overlay.vue
<script setup lang="ts">
import { Dialog as ArkDialog } from "@ark-ui/vue/dialog";
import { computed, inject, useAttrs } from "vue";
import { cn } from "@/lib/utils";
import { dialogOverlayVariants } from "../_shark/dialog.contract";
import { dialogPresentationKey } from "./dialog-context";

defineOptions({ inheritAttrs: false });
const attrs = useAttrs();
const presentation = inject(dialogPresentationKey, { modal: true });
const forwardedAttrs = computed(() => {
  const { class: _className, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <ArkDialog.Backdrop
    v-if="presentation.modal"
    v-bind="forwardedAttrs"
    :class="cn(dialogOverlayVariants(), attrs.class as string | undefined)"
    data-slot="dialog-overlay"
  />
</template>

// registry/svelte/components/dialog/dialog-overlay.svelte
<script lang="ts">
import { Dialog as ArkDialog } from "@ark-ui/svelte/dialog";
import { getContext, type ComponentProps } from "svelte";
import { cn } from "@/lib/utils";
import { dialogOverlayVariants } from "../_shark/dialog.contract";
import {
  dialogPresentationKey,
  type DialogPresentationContext,
} from "./dialog-context";

type Props = ComponentProps<typeof ArkDialog.Backdrop> & { class?: string };
let { class: className, ...rest }: Props = $props();
const presentation = getContext<DialogPresentationContext>(
  dialogPresentationKey
);
</script>

{#if presentation.modal}
  <ArkDialog.Backdrop {...rest} class={cn(dialogOverlayVariants(), className)} data-slot="dialog-overlay" />
{/if}
