// registry/svelte/components/dialog/dialog-footer.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import type { HTMLAttributes } from "svelte/elements";
import { cn } from "@/lib/utils";

type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
  children?: Snippet;
  class?: string;
};
let { children, class: className, ...rest }: Props = $props();
</script>

<div
  {...rest}
  class={cn(
    'shrink-0',
    'flex flex-col-reverse gap-2 sm:flex-row sm:justify-end',
    'sm:rounded-b-[calc(var(--radius-2xl)-1px)]',
    'px-(--space) py-4',
    'bg-muted/48',
    'border-t',
    className,
  )}
  data-slot="dialog-footer"
>{@render children?.()}</div>

// registry/vue/components/dialog/dialog-footer.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { cn } from "@/lib/utils";

defineOptions({ inheritAttrs: false });
const attrs = useAttrs();
const forwardedAttrs = computed(() => {
  const { class: _className, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <div
    v-bind="forwardedAttrs"
    :class="cn(
      'shrink-0',
      'flex flex-col-reverse gap-2 sm:flex-row sm:justify-end',
      'sm:rounded-b-[calc(var(--radius-2xl)-1px)]',
      'px-(--space) py-4',
      'bg-muted/48',
      'border-t',
      attrs.class as string | undefined,
    )"
    data-slot="dialog-footer"
  ><slot /></div>
</template>
