// registry/svelte/components/dialog/dialog.svelte
<script lang="ts">
import { Dialog as ArkDialog } from "@ark-ui/svelte/dialog";
import { setContext, type ComponentProps } from "svelte";
import {
  dialogPresentationKey,
  type DialogPresentationContext,
} from "./dialog-context";

type Props = ComponentProps<typeof ArkDialog.Root>;
let {
  children,
  lazyMount = true,
  modal = true,
  open = $bindable(),
  unmountOnExit = true,
  ...rest
}: Props = $props();

setContext<DialogPresentationContext>(dialogPresentationKey, {
  get modal() {
    return modal;
  },
});
</script>

<ArkDialog.Root bind:open {...rest} {lazyMount} {modal} {unmountOnExit}>
  {@render children?.()}
</ArkDialog.Root>

// registry/vue/components/dialog/dialog.vue
<script setup lang="ts">
import { Dialog as ArkDialog } from "@ark-ui/vue/dialog";
import { computed, provide, useAttrs } from "vue";
import { dialogPresentationKey } from "./dialog-context";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    lazyMount?: boolean;
    modal?: boolean;
    unmountOnExit?: boolean;
  }>(),
  {
    lazyMount: true,
    modal: true,
    unmountOnExit: true,
  }
);
const attrs = useAttrs();
const rootProps = computed(() => ({ ...attrs, ...props }));
provide(dialogPresentationKey, { modal: props.modal });
</script>

<template>
  <ArkDialog.Root v-bind="rootProps">
    <slot />
  </ArkDialog.Root>
</template>
