// registry/svelte/components/dialog/dialog-header.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import type { HTMLAttributes } from "svelte/elements";
import { cn } from "@/lib/utils";
import DialogDescription from "./dialog-description.svelte";
import DialogTitle from "./dialog-title.svelte";

type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
  children?: Snippet;
  class?: string;
  description?: string;
  title?: string;
};
let {
  children,
  class: className,
  description,
  title,
  ...rest
}: Props = $props();
</script>

<div
  {...rest}
  class={cn(
    'shrink-0',
    'p-(--space)',
    'flex flex-col gap-2',
    'in-[[data-slot=dialog-content]:has([data-slot=dialog-body])]:pb-3',
    className,
  )}
  data-slot="dialog-header"
>
  {#if title}<DialogTitle>{title}</DialogTitle>{/if}
  {#if description}<DialogDescription>{description}</DialogDescription>{/if}
  {#if !title}{@render children?.()}{/if}
</div>

// registry/vue/components/dialog/dialog-header.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { cn } from "@/lib/utils";
import DialogDescription from "./dialog-description.vue";
import DialogTitle from "./dialog-title.vue";

defineOptions({ inheritAttrs: false });
interface DialogHeaderProps {
  description?: string;
  title?: string;
}
defineProps<DialogHeaderProps>();
const attrs = useAttrs();
const forwardedAttrs = computed(() => {
  const { class: _className, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <div
    v-bind="forwardedAttrs"
    :class="cn(
      'shrink-0',
      'p-(--space)',
      'flex flex-col gap-2',
      'in-[[data-slot=dialog-content]:has([data-slot=dialog-body])]:pb-3',
      attrs.class as string | undefined,
    )"
    data-slot="dialog-header"
  >
    <DialogTitle v-if="title">{{ title }}</DialogTitle>
    <DialogDescription v-if="description">{{ description }}</DialogDescription>
    <slot v-if="!title" />
  </div>
</template>
