// registry/svelte/components/checkbox/checkbox-group.svelte
<script lang="ts">
import { Checkbox as ArkCheckbox } from "@ark-ui/svelte/checkbox";
import type { ComponentProps } from "svelte";
import { cn } from "@/lib/utils";

type Props = ComponentProps<typeof ArkCheckbox.Group> & { class?: string };
let { class: className, children, ...rest }: Props = $props();
</script>

<ArkCheckbox.Group {...rest} class={cn('flex flex-col gap-2', className)} data-slot="checkbox-group">
  {@render children?.()}
</ArkCheckbox.Group>

// registry/vue/components/checkbox/checkbox-group.vue
<script setup lang="ts">
import { Checkbox as ArkCheckbox } from "@ark-ui/vue/checkbox";
import { computed, useAttrs } from "vue";
import { cn } from "@/lib/utils";

defineOptions({ inheritAttrs: false });
const attrs = useAttrs();
const forwardedAttrs = computed(() => {
  const { class: _className, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <ArkCheckbox.Group
    v-bind="forwardedAttrs"
    :class="cn('flex flex-col gap-2', attrs.class as string | undefined)"
    data-slot="checkbox-group"
  >
    <slot />
  </ArkCheckbox.Group>
</template>
