// registry/solid/components/menu.tsx
import { ark } from "@ark-ui/solid/factory";
import {
  Menu as ArkMenu,
  type MenuContentProps,
  useMenuContext,
} from "@ark-ui/solid/menu";
import { CheckIcon, ChevronRight } from "lucide-solid";
import type { ComponentProps } from "solid-js";

import { tv, type VariantProps } from "tailwind-variants";
import { cn } from "@/lib/utils";

export const useMenu = useMenuContext;

export const Menu = (props: ComponentProps<typeof ArkMenu.Root>) => {
  const {
    lazyMount = true,
    positioning = { placement: "bottom-end" },
    unmountOnExit = true,
    ...rest
  } = props;

  return (
    <ArkMenu.Root
      data-slot="menu"
      lazyMount={lazyMount}
      positioning={positioning}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};

export const MenuTrigger = (props: ComponentProps<typeof ArkMenu.Trigger>) => (
  <ArkMenu.Trigger data-slot="menu-trigger" {...props} />
);

export const MenuPositioner = (
  props: ComponentProps<typeof ArkMenu.Positioner>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkMenu.Positioner
      class={cn("outline-none", className)}
      data-slot="menu-positioner"
      {...rest}
    />
  );
};

export const menuContentVariants = tv({
  base: [
    "z-[calc(50+var(--nested-layer-count,0))]",
    "max-h-(--available-height) not-[class*='w-']:min-w-32",
    "p-1",
    "bg-popover",
    "text-popover-foreground",
    "rounded-xl border shadow-lg/5",
    "origin-(--transform-origin)",
    "outline-none",
    "overflow-y-auto",
    "duration-100",
    "data-[state=open]:animate-in",
    "data-[state=open]:fade-in-0",
    "data-[state=open]:zoom-in-[98%]",
    "data-[placement=bottom]:slide-in-from-top-2",
    "data-[placement=left]:slide-in-from-end-2",
    "data-[placement=right]:slide-in-from-start-2",
    "data-[placement=top]:slide-in-from-bottom-2",
  ],
});

export const MenuContent = (props: MenuContentProps) => {
  const { class: className, children, ...rest } = props;

  return (
    <>
      <MenuPositioner>
        <ArkMenu.Content
          class={cn(menuContentVariants(), className)}
          data-slot="menu-content"
          {...rest}
        >
          {children}
        </ArkMenu.Content>
      </MenuPositioner>
    </>
  );
};

interface MenuGroupProps extends ComponentProps<typeof ArkMenu.ItemGroup> {
  /**
   * The heading of the menu item group.
   */
  heading?: string;
}

export const MenuGroup = (props: MenuGroupProps) => {
  const { heading, children, ...rest } = props;

  return (
    <ArkMenu.ItemGroup data-slot="menu-group" {...rest}>
      {!!heading && <MenuGroupLabel>{heading}</MenuGroupLabel>}

      {children}
    </ArkMenu.ItemGroup>
  );
};

export const MenuSeparator = (
  props: ComponentProps<typeof ArkMenu.Separator>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkMenu.Separator
      class={cn("my-1 h-px bg-border", className)}
      data-slot="menu-separator"
      {...rest}
    />
  );
};

const menuItemVariants = tv({
  base: [
    "group/menu-item",
    "relative",
    "w-full",
    "px-2.5 py-1.5",
    "flex items-center gap-2",
    "select-none text-sm",
    "rounded-lg",
    "outline-hidden",
    "group-data-[date=open]/trigger-item:bg-accent group-data-[date=open]/trigger-item:text-accent-foreground",
    "data-disabled:pointer-events-none data-disabled:opacity-64",
    "[&_svg:not([class*='size-'])]:size-3.5 [&_svg:not([class*='text-'])]:text-muted-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0",
  ],
  variants: {
    variant: {
      default: [
        "data-highlighted:bg-accent data-highlighted:text-accent-foreground",
      ],
      destructive: [
        "text-destructive dark:text-destructive-foreground",
        "data-highlighted:bg-destructive/10 dark:data-highlighted:bg-destructive-foreground/10",
        "**:[svg]:text-destructive! dark:**:[svg]:text-destructive-foreground!",
      ],
    },
  },
  defaultVariants: {
    variant: "default",
  },
});

interface MenuItemProps
  extends ComponentProps<typeof ArkMenu.Item>,
    VariantProps<typeof menuItemVariants> {}

export const MenuItem = (props: MenuItemProps) => {
  const { variant = "default", className, ...rest } = props;

  return (
    <ArkMenu.Item
      class={cn(menuItemVariants({ variant }), className)}
      data-variant={variant}
      {...rest}
    />
  );
};

export const MenuQuickItem = (props: MenuItemProps) => {
  const { variant = "default", className, ...rest } = props;

  return (
    <ArkMenu.Item
      class={cn(
        menuItemVariants({ variant }),
        "flex-col gap-1",
        "[&_svg:not([class*='size-'])]:size-4.5",
        className
      )}
      {...rest}
    />
  );
};

export const MenuCheckboxItem = (
  props: ComponentProps<typeof ArkMenu.CheckboxItem>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkMenu.CheckboxItem
      class={cn(menuItemVariants({ variant: "default" }), "ps-8", className)}
      {...rest}
    >
      <ArkMenu.ItemIndicator class="pointer-events-none absolute inset-s-2 flex size-3.5 items-center justify-center">
        <CheckIcon />
      </ArkMenu.ItemIndicator>

      <ArkMenu.ItemText>{children}</ArkMenu.ItemText>
    </ArkMenu.CheckboxItem>
  );
};

interface MenuRadioGroupProps
  extends ComponentProps<typeof ArkMenu.RadioItemGroup> {
  /**
   * The heading of the menu radio item group.
   */
  heading?: string;
}

export const MenuRadioGroup = (props: MenuRadioGroupProps) => {
  const { heading, children, ...rest } = props;

  return (
    <ArkMenu.RadioItemGroup data-slot="menu-radio-group" {...rest}>
      {!!heading && <MenuGroupLabel>{heading}</MenuGroupLabel>}

      {children}
    </ArkMenu.RadioItemGroup>
  );
};

export const MenuGroupLabel = (
  props: ComponentProps<typeof ArkMenu.ItemGroupLabel>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkMenu.ItemGroupLabel
      class={cn(
        "px-2 py-1.5",
        "font-medium text-muted-foreground text-sm",
        "pointer-events-none",
        className
      )}
      data-slot="menu-group-label"
      {...rest}
    />
  );
};

export const MenuRadioItem = (
  props: ComponentProps<typeof ArkMenu.RadioItem>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkMenu.RadioItem
      class={cn(menuItemVariants({ variant: "default" }), "ps-8", className)}
      data-slot="menu-radio-item"
      {...rest}
    >
      <ArkMenu.ItemIndicator class="pointer-events-none absolute inset-s-2 flex size-3.5 items-center justify-center">
        <CheckIcon />
      </ArkMenu.ItemIndicator>

      <ArkMenu.ItemText data-slot="menu-radio-item-text">
        {children}
      </ArkMenu.ItemText>
    </ArkMenu.RadioItem>
  );
};

export const MenuSub = (props: ComponentProps<typeof Menu>) => (
  <Menu data-slot="menu-sub" {...props} />
);

export const MenuSubContent = (
  props: ComponentProps<typeof ArkMenu.Content>
) => {
  const { class: className, ...rest } = props;

  return (
    <>
      <MenuPositioner data-slot="menu-sub-positioner">
        <ArkMenu.Content
          class={cn(menuContentVariants(), className)}
          data-slot="menu-sub-content"
          {...rest}
        />
      </MenuPositioner>
    </>
  );
};

export const MenuSubTrigger = (
  props: ComponentProps<typeof ArkMenu.TriggerItem>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkMenu.TriggerItem
      class={cn(menuItemVariants({ variant: "default" }), className)}
      data-slot="menu-sub-trigger"
      {...rest}
    >
      {children}

      <MenuShortcut>
        <ChevronRight />
      </MenuShortcut>
    </ArkMenu.TriggerItem>
  );
};

export const MenuShortcut = (props: ComponentProps<typeof ark.span>) => {
  const { class: className, ...rest } = props;

  return (
    <ark.span
      class={cn(
        "ms-auto rtl:me-auto",
        "text-muted-foreground text-xs tracking-widest",
        "group-data-highlighted/menu-item:group-data-[variant=destructive]/menu-item:text-destructive dark:group-data-highlighted/menu-item:group-data-[variant=destructive]/menu-item:text-destructive-foreground",
        className
      )}
      data-slot="menu-shortcut"
      {...rest}
    />
  );
};

export const MenuArrow = (props: ComponentProps<typeof ArkMenu.Arrow>) => {
  const { style, ...rest } = props;

  return (
    <ArkMenu.Arrow
      style={
        {
          "--arrow-background": "var(--popover)",
          "--arrow-size": "calc(1.5 * var(--spacing))",
          ...style,
          left: "20px",
        } as React.CSSProperties
      }
      {...rest}
    >
      <ArkMenu.ArrowTip class="border-s border-t" />
    </ArkMenu.Arrow>
  );
};

// components/ui/menu.tsx
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import { Portal } from "@ark-ui/react/portal";
import { cn } from "fumadocs-ui/utils/cn";
import React from "react";
import { tv, type VariantProps } from "tailwind-variants";

const menuVariants = tv({
  slots: {
    root: "relative",
    trigger: [
      "inline-flex items-center justify-center rounded-md font-medium text-sm",
      "transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
      "disabled:pointer-events-none disabled:opacity-50",
      "bg-background hover:bg-accent hover:text-accent-foreground",
      "h-10 px-4 py-2",
    ],
    contextTrigger: [
      "inline-flex items-center justify-center rounded-md font-medium text-sm",
      "transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
      "disabled:pointer-events-none disabled:opacity-50",
      "bg-background hover:bg-accent hover:text-accent-foreground",
      "h-10 px-4 py-2",
    ],
    positioner: "relative z-50",
    content: [
      "z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md",
      "data-[state=closed]:animate-out data-[state=open]:animate-in",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      "data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95",
      "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2",
      "data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
    ],
    item: [
      "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none",
      "transition-colors focus:bg-accent focus:text-accent-foreground",
      "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
    ],
    itemText: "flex-1",
    itemIndicator: "ml-auto h-4 w-4",
    itemGroup: "px-1 py-1.5",
    itemGroupLabel: [
      "px-2 py-1.5 font-semibold text-foreground text-sm",
      "first:mt-0 last:mb-0",
    ],
    separator: "my-1 h-px bg-muted",
    arrow: "fill-popover",
    arrowTip: "fill-popover",
  },
});

const {
  root,
  trigger,
  contextTrigger,
  positioner,
  content,
  item,
  itemText,
  itemIndicator,
  itemGroup,
  itemGroupLabel,
  separator,
  arrow,
  arrowTip,
} = menuVariants();

export interface MenuProps
  extends React.ComponentProps<typeof ArkMenu.Root>,
    VariantProps<typeof menuVariants> {}

const MenuRoot = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Root>,
  MenuProps
>(({ className, ...props }, ref) => (
  <ArkMenu.Root className={cn(root(), className)} ref={ref} {...props} />
));
MenuRoot.displayName = "Menu";

const MenuTrigger = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Trigger>,
  React.ComponentProps<typeof ArkMenu.Trigger>
>(({ className, ...props }, ref) => (
  <ArkMenu.Trigger className={cn(trigger(), className)} ref={ref} {...props} />
));
MenuTrigger.displayName = "MenuTrigger";

const MenuContextTrigger = React.forwardRef<
  React.ElementRef<typeof ArkMenu.ContextTrigger>,
  React.ComponentProps<typeof ArkMenu.ContextTrigger>
>(({ className, ...props }, ref) => (
  <ArkMenu.ContextTrigger
    className={cn(contextTrigger(), className)}
    ref={ref}
    {...props}
  />
));
MenuContextTrigger.displayName = "MenuContextTrigger";

const MenuPositioner = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Positioner>,
  React.ComponentProps<typeof ArkMenu.Positioner>
>(({ className, ...props }, ref) => (
  <ArkMenu.Positioner
    className={cn(positioner(), className)}
    ref={ref}
    {...props}
  />
));
MenuPositioner.displayName = "MenuPositioner";

const MenuContent = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Content>,
  React.ComponentProps<typeof ArkMenu.Content>
>(({ className, ...props }, ref) => (
  <Portal>
    <ArkMenu.Content
      className={cn(content(), className)}
      ref={ref}
      {...props}
    />
  </Portal>
));
MenuContent.displayName = "MenuContent";

const MenuItem = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Item>,
  React.ComponentProps<typeof ArkMenu.Item>
>(({ className, ...props }, ref) => (
  <ArkMenu.Item className={cn(item(), className)} ref={ref} {...props} />
));
MenuItem.displayName = "MenuItem";

const MenuItemText = React.forwardRef<
  React.ElementRef<typeof ArkMenu.ItemText>,
  React.ComponentProps<typeof ArkMenu.ItemText>
>(({ className, ...props }, ref) => (
  <ArkMenu.ItemText
    className={cn(itemText(), className)}
    ref={ref}
    {...props}
  />
));
MenuItemText.displayName = "MenuItemText";

const MenuItemIndicator = React.forwardRef<
  React.ElementRef<typeof ArkMenu.ItemIndicator>,
  React.ComponentProps<typeof ArkMenu.ItemIndicator>
>(({ className, ...props }, ref) => (
  <ArkMenu.ItemIndicator
    className={cn(itemIndicator(), className)}
    ref={ref}
    {...props}
  />
));
MenuItemIndicator.displayName = "MenuItemIndicator";

const MenuItemGroup = React.forwardRef<
  React.ElementRef<typeof ArkMenu.ItemGroup>,
  React.ComponentProps<typeof ArkMenu.ItemGroup>
>(({ className, ...props }, ref) => (
  <ArkMenu.ItemGroup
    className={cn(itemGroup(), className)}
    ref={ref}
    {...props}
  />
));
MenuItemGroup.displayName = "MenuItemGroup";

const MenuItemGroupLabel = React.forwardRef<
  React.ElementRef<typeof ArkMenu.ItemGroupLabel>,
  React.ComponentProps<typeof ArkMenu.ItemGroupLabel>
>(({ className, ...props }, ref) => (
  <ArkMenu.ItemGroupLabel
    className={cn(itemGroupLabel(), className)}
    ref={ref}
    {...props}
  />
));
MenuItemGroupLabel.displayName = "MenuItemGroupLabel";

const MenuSeparator = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Separator>,
  React.ComponentProps<typeof ArkMenu.Separator>
>(({ className, ...props }, ref) => (
  <ArkMenu.Separator
    className={cn(separator(), className)}
    ref={ref}
    {...props}
  />
));
MenuSeparator.displayName = "MenuSeparator";

const MenuArrow = React.forwardRef<
  React.ElementRef<typeof ArkMenu.Arrow>,
  React.ComponentProps<typeof ArkMenu.Arrow>
>(({ className, ...props }, ref) => (
  <ArkMenu.Arrow className={cn(arrow(), className)} ref={ref} {...props} />
));
MenuArrow.displayName = "MenuArrow";

const MenuArrowTip = React.forwardRef<
  React.ElementRef<typeof ArkMenu.ArrowTip>,
  React.ComponentProps<typeof ArkMenu.ArrowTip>
>(({ className, ...props }, ref) => (
  <ArkMenu.ArrowTip
    className={cn(arrowTip(), className)}
    ref={ref}
    {...props}
  />
));
MenuArrowTip.displayName = "MenuArrowTip";

// Checkbox and Radio components
const MenuCheckboxItem = React.forwardRef<
  React.ElementRef<typeof ArkMenu.CheckboxItem>,
  React.ComponentProps<typeof ArkMenu.CheckboxItem>
>(({ className, children, ...props }, ref) => (
  <ArkMenu.CheckboxItem className={cn(item(), className)} ref={ref} {...props}>
    <MenuItemIndicator>
      <svg
        className="h-4 w-4"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          d="M5 13l4 4L19 7"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
        />
      </svg>
    </MenuItemIndicator>
    <MenuItemText>{children}</MenuItemText>
  </ArkMenu.CheckboxItem>
));
MenuCheckboxItem.displayName = "MenuCheckboxItem";

const MenuRadioItemGroup = React.forwardRef<
  React.ElementRef<typeof ArkMenu.RadioItemGroup>,
  React.ComponentProps<typeof ArkMenu.RadioItemGroup>
>(({ className, ...props }, ref) => (
  <ArkMenu.RadioItemGroup
    className={cn(itemGroup(), className)}
    ref={ref}
    {...props}
  />
));
MenuRadioItemGroup.displayName = "MenuRadioItemGroup";

const MenuRadioItem = React.forwardRef<
  React.ElementRef<typeof ArkMenu.RadioItem>,
  React.ComponentProps<typeof ArkMenu.RadioItem>
>(({ className, children, ...props }, ref) => (
  <ArkMenu.RadioItem className={cn(item(), className)} ref={ref} {...props}>
    <MenuItemIndicator>
      <div className="h-2 w-2 rounded-full bg-current" />
    </MenuItemIndicator>
    <MenuItemText>{children}</MenuItemText>
  </ArkMenu.RadioItem>
));
MenuRadioItem.displayName = "MenuRadioItem";

export const Menu = {
  Root: MenuRoot,
  Trigger: MenuTrigger,
  ContextTrigger: MenuContextTrigger,
  Positioner: MenuPositioner,
  Content: MenuContent,
  Item: MenuItem,
  ItemText: MenuItemText,
  ItemIndicator: MenuItemIndicator,
  ItemGroup: MenuItemGroup,
  ItemGroupLabel: MenuItemGroupLabel,
  Separator: MenuSeparator,
  Arrow: MenuArrow,
  ArrowTip: MenuArrowTip,
  CheckboxItem: MenuCheckboxItem,
  RadioItemGroup: MenuRadioItemGroup,
  RadioItem: MenuRadioItem,
};
