// registry/solid/components/tabs.tsx
import { Tabs as ArkTabs, useTabsContext } from "@ark-ui/solid/tabs";
import type { ComponentProps } from "solid-js";

import { tv, type VariantProps } from "tailwind-variants";
import { cn } from "@/lib/utils";

export const useTabs = useTabsContext;

export const Tabs = (props: ComponentProps<typeof ArkTabs.Root>) => {
  const { lazyMount = true, unmountOnExit = true, className, ...rest } = props;

  return (
    <ArkTabs.Root
      class={cn(
        "flex flex-col gap-2",
        "data-[orientation=vertical]:flex-row",
        className
      )}
      data-slot="tabs"
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};

const tabsListVariants = tv({
  slots: {
    base: [
      "relative z-0",
      "w-fit",
      "text-muted-foreground",
      "flex items-center justify-center gap-x-0.5",
      "data-[orientation=vertical]:flex-col",
    ],
    indicator: [
      "absolute inset-s-0 bottom-0",
      "h-(--height) w-(--width)",
      "transition-[width,translate] duration-200 ease-in-out",
    ],
  },
  variants: {
    variant: {
      default: {
        base: ["rounded-lg"],
        indicator: ["-z-1 rounded-lg bg-input/64 dark:bg-input"],
      },
      underline: {
        base: [
          "data-[orientation=vertical]:px-1",
          "data-[orientation=horizontal]:py-1",
          "*:data-[slot=tabs-tab]:hover:bg-accent",
        ],
        indicator: [
          "z-10",
          "absolute bottom-0",
          "bg-primary",
          "data-[orientation=horizontal]:h-0.5",
          "data-[orientation=vertical]:w-0.5",
        ],
      },
    },
  },
  defaultVariants: {
    variant: "default",
  },
});
interface TabsListProps
  extends ComponentProps<typeof ArkTabs.List>,
    VariantProps<typeof tabsListVariants> {}

export const TabsList = (props: TabsListProps) => {
  const { variant = "default", className, children, ...rest } = props;

  const { base, indicator } = tabsListVariants({ variant });

  return (
    <ArkTabs.List class={cn(base(), className)} data-slot="tabs-list" {...rest}>
      {children}

      <ArkTabs.Indicator class={cn(indicator())} data-slot="tab-indicator" />
    </ArkTabs.List>
  );
};

export const TabsTrigger = (props: ComponentProps<typeof ArkTabs.Trigger>) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTabs.Trigger
      class={cn(
        "relative",
        "h-9 sm:h-8",
        "flex shrink-0 grow items-center justify-center gap-1.5",
        "px-[calc(--spacing(2.5)-1px)]",
        "whitespace-nowrap font-medium text-base sm:text-sm",
        "rounded-lg border border-transparent",
        "cursor-pointer",
        "transition-[color,background-color,box-shadow]",
        "data-[orientation=vertical]:w-full data-[orientation=vertical]:justify-start",
        "hover:text-foreground/72",
        "aria-selected:text-foreground",
        "outline-none focus-visible:border-primary focus-visible:ring-[3px] focus-visible:ring-ring/32",
        "data-disabled:pointer-events-none data-disabled:opacity-64",
        "[&_svg:not([class*='size-'])]:size-4.5 sm:[&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:-mx-0.5 [&_svg]:shrink-0",
        className
      )}
      data-slot="tabs-trigger"
      {...rest}
    />
  );
};

export const TabsContent = (props: ComponentProps<typeof ArkTabs.Content>) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTabs.Content
      class={cn("flex-1 outline-none", className)}
      data-slot="tabs-content"
      {...rest}
    />
  );
};

// components/ui/tabs.tsx
import { Tabs as ArkTabs } from "@ark-ui/react/tabs";
import { cn } from "fumadocs-ui/utils/cn";
import type React from "react";

export const Tabs = (props: React.ComponentProps<typeof ArkTabs.Root>) => {
  const { className, ...rest } = props;
  return (
    <ArkTabs.Root
      className={cn("flex flex-col gap-2", className)}
      data-slot="tabs"
      {...rest}
    />
  );
};

export const TabsList = (props: React.ComponentProps<typeof ArkTabs.List>) => {
  const { className, ...rest } = props;

  return (
    <ArkTabs.List
      className={cn(
        "relative",
        "h-9 w-fit p-1",
        "inline-flex items-center justify-center",
        "bg-muted",
        "text-muted-foreground",
        "rounded-lg",
        className
      )}
      data-slot="tab-list"
      {...rest}
    />
  );
};

export const TabsTrigger = (
  props: React.ComponentProps<typeof ArkTabs.Trigger>
) => {
  const { className, ...rest } = props;

  return (
    <ArkTabs.Trigger
      className={cn(
        "h-[calc(100%-1px)] px-2 py-1",
        "inline-flex flex-1 items-center justify-center gap-1.5",
        "whitespace-nowrap font-medium text-muted-foreground text-sm",
        "rounded-md border border-transparent",
        "transition-[color,box-shadow]",
        "focus-visible:border-ring focus-visible:outline-1 focus-visible:outline-ring focus-visible:ring-[3px] focus-visible:ring-ring/50",
        "disabled:pointer-events-none disabled:opacity-50",
        "aria-selected:text-foreground",
        // "aria-selected:bg-background aria-selected:shadow-sm",
        "[&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        className
      )}
      data-slot="tab-trigger"
      {...rest}
    />
  );
};

export const TabsIndicator = (
  props: React.ComponentProps<typeof ArkTabs.Indicator>
) => {
  const { className, ...rest } = props;

  return (
    <ArkTabs.Indicator
      className={cn(
        "absolute bottom-0 h-0.5 w-[var(--width)] bg-primary",
        className
      )}
      data-slot="tab-indicator"
      {...rest}
    />
  );
};

export const TabsContent = (
  props: React.ComponentProps<typeof ArkTabs.Content>
) => {
  const { className, ...rest } = props;

  return (
    <ArkTabs.Content
      className={cn("flex-1 outline-none", className)}
      data-slot="tab-content"
      {...rest}
    />
  );
};
