// registry/solid/components/kbd.tsx
import { ark } from "@ark-ui/solid/factory";
import type { ComponentProps } from "solid-js";

import { tv, type VariantProps } from "tailwind-variants";
import { cn } from "@/lib/utils";

const kbdVariants = tv({
  base: [
    "h-5 min-w-5",
    "px-1",
    "inline-flex items-center justify-center gap-1",
    "select-none font-medium font-sans text-foreground text-xs",
    "rounded-sm border border-transparent",
    "pointer-events-none",
    "in-data-[slot=tooltip-content]:bg-background/20 in-data-[slot=tooltip-content]:text-background",
    "[&_svg:not([class*='size-'])]:size-3",
  ],
  variants: {
    variant: {
      default: "bg-muted",
      outline: "border border-border",
    },
  },
  defaultVariants: {
    variant: "default",
  },
});

interface KbdProps
  extends ComponentProps<typeof ark.kbd>,
    VariantProps<typeof kbdVariants> {}

export const Kbd = (props: KbdProps) => {
  const { variant = "default", className, ...rest } = props;

  return (
    <ark.kbd
      class={cn(kbdVariants({ variant }), className)}
      data-slot="kbd"
      {...rest}
    />
  );
};

export const KbdGroup = (props: ComponentProps<typeof ark.div>) => {
  const { class: className, ...rest } = props;

  return (
    <ark.div
      class={cn("inline-flex items-center gap-1", className)}
      data-slot="kbd-group"
      {...rest}
    />
  );
};

// components/thumbs/kbd.tsx
import { BlockThumbCard } from "./block-card";
import type { ThumbProps } from "./types";

export const KbdThumb = ({ description = "", title = "Kbd" }: ThumbProps) => (
  <BlockThumbCard subtitle={description} title={title}>
    <div className="flex justify-center gap-1.5">
      <div className="flex size-12 items-center justify-center rounded-lg border bg-muted shadow-md/5">
        <span
          aria-hidden
          className="font-medium text-base text-muted-foreground"
        >
          ⌘
        </span>
      </div>
      <div className="flex size-12 items-center justify-center rounded-lg border bg-muted shadow-md/5">
        <span
          aria-hidden
          className="font-medium text-base text-muted-foreground"
        >
          K
        </span>
      </div>
    </div>
  </BlockThumbCard>
);
