// registry/solid/components/aspect-ratio.tsx
import { ark } from "@ark-ui/solid/factory";
import type { ComponentProps } from "solid-js";

import { cn } from "@/lib/utils";

interface AspectRatioProps extends ComponentProps<typeof ark.div> {}

export const AspectRatio = (props: AspectRatioProps) => {
  const { class: className, ...rest } = props;

  return (
    <ark.div
      class={cn(
        "[--ratio:1]",
        "relative",
        "w-full",
        "aspect-(--ratio)",
        className
      )}
      data-slot="aspect-ratio"
      {...rest}
    />
  );
};

// registry/react/components/aspect-ratio.tsx
import { ark } from "@ark-ui/react/factory";
import type React from "react";
import { cn } from "@/lib/utils";

interface AspectRatioProps extends React.ComponentProps<typeof ark.div> {}

export const AspectRatio = (props: AspectRatioProps) => {
  const { className, ...rest } = props;

  return (
    <ark.div
      className={cn(
        "[--ratio:1]",
        "relative",
        "w-full",
        "aspect-(--ratio)",
        className
      )}
      data-slot="aspect-ratio"
      {...rest}
    />
  );
};
