// registry/solid/components/download-trigger.tsx
import { DownloadTrigger as ArkDownloadTrigger } from "@ark-ui/solid/download-trigger";
import type { ComponentProps } from "solid-js";

export const DownloadTrigger = (
  props: ComponentProps<typeof ArkDownloadTrigger>
) => {
  return <ArkDownloadTrigger data-slot="download-trigger" {...props} />;
};

// registry/react/components/download-trigger.tsx
"use client";

import { DownloadTrigger as ArkDownloadTrigger } from "@ark-ui/react/download-trigger";
import type React from "react";

export const DownloadTrigger = (
  props: React.ComponentProps<typeof ArkDownloadTrigger>
) => {
  return <ArkDownloadTrigger data-slot="download-trigger" {...props} />;
};
