// registry/solid/components/format.tsx
import { Format as ArkFormat } from "@ark-ui/solid/format";
import type { ComponentProps } from "solid-js";

export const FormatByte = (props: ComponentProps<typeof ArkFormat.Byte>) => {
  return <ArkFormat.Byte data-slot="format-byte" {...props} />;
};

export const FormatNumber = (
  props: ComponentProps<typeof ArkFormat.Number>
) => {
  return <ArkFormat.Number data-slot="format-number" {...props} />;
};

export const FormatRelativeTime = (
  props: ComponentProps<typeof ArkFormat.RelativeTime>
) => {
  return <ArkFormat.RelativeTime data-slot="format-relative-time" {...props} />;
};

// registry/react/components/format.tsx
"use client";

import { Format as ArkFormat } from "@ark-ui/react/format";

export const FormatByte = (
  props: React.ComponentProps<typeof ArkFormat.Byte>
) => <ArkFormat.Byte data-slot="format-byte" {...props} />;

export const FormatNumber = (
  props: React.ComponentProps<typeof ArkFormat.Number>
) => <ArkFormat.Number data-slot="format-number" {...props} />;

export const FormatRelativeTime = (
  props: React.ComponentProps<typeof ArkFormat.RelativeTime>
) => <ArkFormat.RelativeTime data-slot="format-relative-time" {...props} />;

export const Format = {
  Byte: FormatByte,
  Number: FormatNumber,
  RelativeTime: FormatRelativeTime,
};
