// registry/solid/components/prose.tsx
import { ark } from "@ark-ui/solid/factory";
import type { ComponentProps } from "solid-js";
import { cn } from "@/lib/utils";

export const Prose = (props: ComponentProps<typeof ark.div>) => {
  const { class: className, ...rest } = props;

  return (
    <ark.div
      class={cn("prose mx-auto max-w-[65ch]", className)}
      data-slot="prose"
      {...rest}
    />
  );
};

// registry/react/components/prose.tsx
import { ark } from "@ark-ui/react/factory";
import { cn } from "@/lib/utils";

export interface ProseProps extends React.ComponentProps<typeof ark.div> {}

export const Prose = (props: ProseProps) => {
  const { className, ...rest } = props;

  return (
    <ark.div
      className={cn("prose mx-auto max-w-[65ch]", className)}
      data-slot="prose"
      {...rest}
    />
  );
};
