// components/ui/accordion.tsx
import { Accordion as ArkAccordion } from "@ark-ui/react/accordion";
import { cn } from "fumadocs-ui/utils/cn";
import React from "react";
import { tv, type VariantProps } from "tailwind-variants";

const accordionVariants = tv({
  slots: {
    root: "w-full",
    item: "border-border border-b",
    trigger: [
      "flex w-full items-center justify-between py-4 font-medium transition-all",
      "hover:bg-accent/50",
      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
      "disabled:pointer-events-none disabled:opacity-50",
      "[&[data-state=open]>svg]:rotate-180",
    ],
    content: [
      "overflow-hidden text-sm transition-all",
      "data-[state=closed]:animate-accordion-up",
      "data-[state=open]:animate-accordion-down",
    ],
    indicator: "h-4 w-4 shrink-0 transition-transform duration-200",
  },
});

const { root, item, trigger, content, indicator } = accordionVariants();

export interface AccordionProps
  extends React.ComponentProps<typeof ArkAccordion.Root>,
    VariantProps<typeof accordionVariants> {}

const AccordionRoot = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.Root>,
  AccordionProps
>(({ className, ...props }, ref) => (
  <ArkAccordion.Root className={cn(root(), className)} ref={ref} {...props} />
));
AccordionRoot.displayName = "Accordion";

const AccordionItem = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.Item>,
  React.ComponentProps<typeof ArkAccordion.Item>
>(({ className, ...props }, ref) => (
  <ArkAccordion.Item className={cn(item(), className)} ref={ref} {...props} />
));
AccordionItem.displayName = "AccordionItem";

const AccordionTrigger = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.ItemTrigger>,
  React.ComponentProps<typeof ArkAccordion.ItemTrigger>
>(({ className, children, ...props }, ref) => (
  <ArkAccordion.ItemTrigger
    className={cn(trigger(), className)}
    ref={ref}
    {...props}
  >
    {children}
  </ArkAccordion.ItemTrigger>
));
AccordionTrigger.displayName = "AccordionTrigger";

const AccordionContent = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.ItemContent>,
  React.ComponentProps<typeof ArkAccordion.ItemContent>
>(({ className, children, ...props }, ref) => (
  <ArkAccordion.ItemContent
    className={cn(content(), className)}
    ref={ref}
    {...props}
  >
    <div className="pt-0 pb-4">{children}</div>
  </ArkAccordion.ItemContent>
));
AccordionContent.displayName = "AccordionContent";

const AccordionIndicator = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.ItemIndicator>,
  React.ComponentProps<typeof ArkAccordion.ItemIndicator>
>(({ className, ...props }, ref) => (
  <ArkAccordion.ItemIndicator
    className={cn(indicator(), className)}
    ref={ref}
    {...props}
  />
));
AccordionIndicator.displayName = "AccordionIndicator";

export const Accordion = {
  Root: AccordionRoot,
  Item: AccordionItem,
  ItemTrigger: AccordionTrigger,
  ItemContent: AccordionContent,
  ItemIndicator: AccordionIndicator,
};

// registry/solid/components/accordion.tsx
import {
  Accordion as ArkAccordion,
  useAccordionContext,
} from "@ark-ui/solid/accordion";
import { ChevronDownIcon } from "lucide-solid";
import type { ComponentProps } from "solid-js";

import { cn } from "@/lib/utils";

export const useAccordion = useAccordionContext;

export const Accordion = (props: ComponentProps<typeof ArkAccordion.Root>) => {
  const {
    collapsible = true,
    lazyMount = true,
    unmountOnExit = true,
    ...rest
  } = props;

  return (
    <ArkAccordion.Root
      collapsible={collapsible}
      data-slot="accordion"
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};

export const AccordionItem = (
  props: ComponentProps<typeof ArkAccordion.Item>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkAccordion.Item
      class={cn("flex flex-col border-b last:border-b-0", className)}
      data-slot="accordion-item"
      {...rest}
    />
  );
};

export const AccordionTrigger = (
  props: ComponentProps<typeof ArkAccordion.ItemTrigger>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkAccordion.ItemTrigger
      class={cn(
        "flex flex-1 items-center justify-between gap-3",
        "py-4",
        "text-left font-medium text-sm",
        "rounded-md border border-transparent",
        "outline-none",
        "transition-all",
        "disabled:pointer-events-none disabled:opacity-64 disabled:grayscale",
        "focus-visible:border-primary focus-visible:ring-[3px] focus-visible:ring-ring/32",
        "[&_[data-state=open]>svg]:rotate-180",
        className
      )}
      data-slot="accordion-trigger"
      {...rest}
    >
      {children}

      <ArkAccordion.ItemIndicator data-slot="accordion-indicator">
        <ChevronDownIcon
          class={cn(
            "translate-y-0.5",
            "size-4",
            "shrink-0",
            "text-muted-foreground",
            "pointer-events-none",
            "transition-transform duration-300"
          )}
        />
      </ArkAccordion.ItemIndicator>
    </ArkAccordion.ItemTrigger>
  );
};

export const AccordionContent = (
  props: ComponentProps<typeof ArkAccordion.ItemContent>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkAccordion.ItemContent
      class={cn(
        "overflow-hidden rounded-md text-sm",
        "data-[state=open]:animate-slide-down",
        "data-[state=closed]:animate-slide-up",
        className
      )}
      data-slot="accordion-content"
      {...rest}
    >
      <div class="pt-0 pb-4">{children}</div>
    </ArkAccordion.ItemContent>
  );
};
