// registry/react/components/datepicker.tsx
import { DatePicker as ArkDatePicker } from "@ark-ui/react/date-picker";
import { ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";
import type React from "react";
import { cn } from "@/lib/utils";
import {
  type InputProps,
  inputVariants,
} from "@/registry/react/components/input";
import { Button } from "./button";

export const DatePicker = (
  props: React.ComponentProps<typeof ArkDatePicker.Root>
) => {
  const { lazyMount = true, unmountOnExit = true, ...rest } = props;

  return (
    <ArkDatePicker.Root
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};

export const DatePickerControl = (
  props: React.ComponentProps<typeof ArkDatePicker.Control>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.Control
      className={cn("inline-flex gap-2.5", className)}
      {...rest}
    />
  );
};

interface DatePickerInputProps
  extends Omit<React.ComponentProps<typeof ArkDatePicker.Input>, "size">,
    Pick<InputProps, "size"> {}

export const DatePickerInput = (props: DatePickerInputProps) => {
  const { size = "md", className, ...rest } = props;

  return (
    <ArkDatePicker.Input
      className={cn(inputVariants({ size }), className)}
      {...rest}
    />
  );
};

export const DatePickerTrigger = (
  props: React.ComponentProps<typeof ArkDatePicker.Trigger>
) => {
  const { className, ...rest } = props;

  return <ArkDatePicker.Trigger asChild className={cn(className)} {...rest} />;
};

export const DatePickerContent = (
  props: React.ComponentProps<typeof ArkDatePicker.Content>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.Content
      className={cn("min-w-72 rounded-lg border p-2", className)}
      {...rest}
    />
  );
};

export const DatePickerYearSelect = (
  props: React.ComponentProps<typeof ArkDatePicker.YearSelect>
) => {
  const { className, ...rest } = props;

  return (
    <span className="relative">
      <ArkDatePicker.YearSelect
        className={cn(
          "appearance-none rounded-md border px-2 py-1 pr-6 text-sm",
          className
        )}
        {...rest}
      />

      <span className="absolute inset-y-0 right-1 flex items-center [&_svg]:size-3.5 [&_svg]:text-muted-foreground">
        <ChevronDown />
      </span>
    </span>
  );
};

export const DatePickerMonthSelect = (
  props: React.ComponentProps<typeof ArkDatePicker.MonthSelect>
) => {
  const { className, ...rest } = props;

  return (
    <span className="relative">
      <ArkDatePicker.MonthSelect
        className={cn(
          "appearance-none rounded-md border px-2 py-1 pr-6 text-sm",
          className
        )}
        {...rest}
      />

      <span className="absolute inset-y-0 right-1 flex items-center [&_svg]:size-3.5 [&_svg]:text-muted-foreground">
        <ChevronDown />
      </span>
    </span>
  );
};

export const DatePickerView = (
  props: React.ComponentProps<typeof ArkDatePicker.View>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.View
      className={cn("flex flex-col gap-2.5", className)}
      {...rest}
    />
  );
};

export const DatePickerContext = (
  props: React.ComponentProps<typeof ArkDatePicker.Context>
) => <ArkDatePicker.Context {...props} />;

export const DatePickerViewControl = (
  props: React.ComponentProps<typeof ArkDatePicker.ViewControl>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.ViewControl
      className={cn("flex items-center justify-between", className)}
      {...rest}
    />
  );
};

export const DatePickerPrevTrigger = (
  props: React.ComponentProps<typeof ArkDatePicker.PrevTrigger>
) => (
  <ArkDatePicker.PrevTrigger asChild {...props}>
    <Button size="icon-sm" variant="ghost">
      <ChevronLeft />
    </Button>
  </ArkDatePicker.PrevTrigger>
);

export const DatePickerNextTrigger = (
  props: React.ComponentProps<typeof ArkDatePicker.NextTrigger>
) => (
  <ArkDatePicker.NextTrigger asChild {...props}>
    <Button size="icon-sm" variant="ghost">
      <ChevronRight />
    </Button>
  </ArkDatePicker.NextTrigger>
);

export const DatePickerViewTrigger = (
  props: React.ComponentProps<typeof ArkDatePicker.ViewTrigger>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.ViewTrigger
      className={cn("rounded border-0 px-5 py-1", className)}
      {...rest}
    />
  );
};

export const DatePickerRangeText = (
  props: React.ComponentProps<typeof ArkDatePicker.RangeText>
) => {
  const { className, ...rest } = props;

  return <ArkDatePicker.RangeText className={cn(className)} {...rest} />;
};

export const DatePickerTable = (
  props: React.ComponentProps<typeof ArkDatePicker.Table>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.Table
      className={cn("w-full min-w-[240px] border-collapse", className)}
      {...rest}
    />
  );
};

export const DatePickerTableHead = (
  props: React.ComponentProps<typeof ArkDatePicker.TableHead>
) => <ArkDatePicker.TableHead {...props} />;

export const DatePickerTableRow = (
  props: React.ComponentProps<typeof ArkDatePicker.TableRow>
) => <ArkDatePicker.TableRow className="mt-2 flex w-full" {...props} />;

export const DatePickerTableHeader = (
  props: React.ComponentProps<typeof ArkDatePicker.TableHeader>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.TableHeader
      className={cn(
        "flex-1 select-none rounded-md font-normal text-[0.8rem] text-muted-foreground",
        className
      )}
      {...rest}
    />
  );
};

export const DatePickerTableBody = (
  props: React.ComponentProps<typeof ArkDatePicker.TableBody>
) => {
  const { className, ...rest } = props;

  return <ArkDatePicker.TableBody className={cn(className)} {...rest} />;
};

export const DatePickerTableCell = (
  props: React.ComponentProps<typeof ArkDatePicker.TableCell>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.TableCell
      className={cn(
        "group/day",
        "size-full",
        "relative",
        "p-0",
        "select-none text-center",
        "aspect-square",
        "[&:first-child[aria-selected=true]_div]:rounded-l-md [&:last-child[aria-selected=true]_div]:rounded-r-md",
        className
      )}
      {...rest}
    />
  );
};

export const DatePickerTableCellTrigger = (
  props: React.ComponentProps<typeof ArkDatePicker.TableCellTrigger>
) => {
  const { className, ...rest } = props;

  return (
    <ArkDatePicker.TableCellTrigger
      className={cn(
        "flex shrink-0 flex-col items-center justify-center gap-1 whitespace-nowrap",
        "aspect-square size-auto w-full min-w-8",
        "select-none font-normal text-foreground text-sm leading-none",
        "transition-[background-color,color]",
        "rounded-md",
        "hover:bg-accent hover:text-accent-foreground",
        "data-today:bg-primary/5 data-today:text-primary",
        "data-focus:bg-accent/30 data-focus:text-primary",
        "outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50",
        "data-disabled:pointer-events-none data-disabled:opacity-20",
        "data-in-range:not-[data-selected]:bg-primary/10",
        "data-selected:bg-primary! data-selected:text-primary-foreground!",
        "aria-invalid:border-destructive aria-invalid:ring-destructive/20",
        "data-hover-range-end:rounded-r-md! data-range-end:rounded-r-md",
        "data-range-start:rounded-l-md",
        "data-in-range:rounded-none",
        "[&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        className
      )}
      {...rest}
    />
  );
};

// registry/solid/components/date-picker.tsx
import {
  DatePicker as ArkDatePicker,
  useDatePickerContext,
} from "@ark-ui/solid/date-picker";
import { CalendarIcon, ClockIcon } from "lucide-solid";
import type { ComponentProps } from "solid-js";

import { cn } from "@/lib/utils";
import { Button } from "@/registry/solid/components/button";
import {
  Calendar,
  CalendarPresetTrigger,
} from "@/registry/solid/components/calendar";
import type { Input, InputProps } from "@/registry/solid/components/input";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput,
} from "@/registry/solid/components/input-group";

export const useDatePicker = useDatePickerContext;

export const DatePicker = (props: ComponentProps<typeof Calendar>) => {
  const { positioning = { placement: "top" }, ...rest } = props;

  return (
    <Calendar
      data-slot="date-picker"
      inline={false}
      positioning={positioning}
      {...rest}
    />
  );
};

export const DatePickerTrigger = (
  props: ComponentProps<typeof ArkDatePicker.Trigger>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkDatePicker.Control data-slot="date-picker-control">
      <ArkDatePicker.Trigger
        class={cn(
          "justify-start",
          "text-left data-placeholder-shown:[&>span]:text-muted-foreground",
          "active:scale-100",
          "[&_svg:not([class*='text-'])]:opacity-64",
          className
        )}
        data-slot="date-picker-trigger"
        {...rest}
      >
        {children}
      </ArkDatePicker.Trigger>
    </ArkDatePicker.Control>
  );
};

interface DatePickerInputProps
  extends Omit<ComponentProps<typeof ArkDatePicker.Input>, "size">,
    InputProps {}

export const DatePickerInput = (props: DatePickerInputProps) => {
  const { size, className, ...rest } = props;

  return (
    <ArkDatePicker.Control data-slot="date-picker-control">
      <InputGroup size={size}>
        <ArkDatePicker.Input asChild data-slot="date-picker-input" {...rest}>
          <InputGroupInput />
        </ArkDatePicker.Input>

        <InputGroupAddon align="inline-end">
          <InputGroupButton
            asChild
            data-slot="input-group-button"
            size="icon-xs"
            variant="ghost"
          >
            <ArkDatePicker.Trigger asChild data-slot="date-picker-trigger">
              <Button size="icon-md" variant="ghost">
                <CalendarIcon aria-hidden class="text-muted-foreground" />
              </Button>
            </ArkDatePicker.Trigger>
          </InputGroupButton>
        </InputGroupAddon>
      </InputGroup>
    </ArkDatePicker.Control>
  );
};

export const DatePickerTimer = (props: ComponentProps<typeof Input>) => {
  const { id, value, defaultValue, className, ...rest } = props;

  return (
    <InputGroup {...rest}>
      <InputGroupAddon>
        <ClockIcon />
      </InputGroupAddon>
      <InputGroupInput
        class={cn(
          "[&::-webkit-calendar-picker-indicator]:hidden [&::-webkit-calendar-picker-indicator]:appearance-none",
          className
        )}
        defaultValue={defaultValue}
        id={id}
        step="1"
        type="time"
        value={value}
      />
    </InputGroup>
  );
};

export const DatePickerContent = (
  props: ComponentProps<typeof ArkDatePicker.Content>
) => {
  const { class: className, ...rest } = props;

  return (
    <>
      <ArkDatePicker.Positioner data-slot="date-picker-positioner">
        <ArkDatePicker.Content
          class={cn(
            "[--cell-size:--spacing(8)]",
            "z-[calc(50+var(--layer-index,0))]",
            "w-fit min-w-72",
            "p-3",
            "bg-popover",
            "text-popover-foreground",
            "rounded-xl border shadow-lg/5",
            "outline-none",
            "origin-(--transform-origin)",
            "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
            "data-[state=closed]:animate-out data-[state=open]:animate-in",
            "data-[state=closed]:zoom-out-[98%] data-[state=open]:zoom-in-[98%]",
            className
          )}
          data-slot="date-picker-content"
          {...rest}
        />
      </ArkDatePicker.Positioner>
    </>
  );
};

export const DatePickerValue = (
  props: ComponentProps<typeof ArkDatePicker.ValueText>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkDatePicker.ValueText
      class={cn("font-medium text-sm", className)}
      data-slot="date-picker-value"
      {...rest}
    />
  );
};

export const DatePickerPresetTrigger = (
  props: ComponentProps<typeof ArkDatePicker.PresetTrigger>
) => {
  return (
    <CalendarPresetTrigger data-slot="date-picker-preset-trigger" {...props} />
  );
};
