// components/ui/dialog.tsx
import { Dialog as ArkDialog } from "@ark-ui/react/dialog";
import { Portal } from "@ark-ui/react/portal";
import { cn } from "fumadocs-ui/utils/cn";
import React from "react";
import { tv, type VariantProps } from "tailwind-variants";

const dialogVariants = tv({
  slots: {
    root: "relative",
    trigger: "inline-flex",
    backdrop: [
      "fixed inset-0 z-50",
      "bg-background/80 backdrop-blur-sm",
      "data-[state=closed]:animate-out data-[state=open]:animate-in",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
    ],
    positioner: ["fixed inset-0 z-50 flex items-center justify-center", "p-4"],
    content: [
      "relative z-50 grid w-full max-w-lg gap-4 border bg-background p-6 shadow-lg",
      "sm:rounded-lg",
      "data-[state=closed]:animate-out data-[state=open]:animate-in",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      "data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95",
      "data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%]",
      "data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%]",
    ],
    title: ["font-semibold text-lg leading-none tracking-tight"],
    description: ["text-muted-foreground text-sm"],
    closeTrigger: [
      "absolute top-4 right-4 rounded-sm opacity-70 ring-offset-background",
      "transition-opacity hover:opacity-100",
      "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
      "disabled:pointer-events-none",
      "data-[state=open]:bg-accent data-[state=open]:text-muted-foreground",
    ],
  },
});

const {
  root,
  trigger,
  backdrop,
  positioner,
  content,
  title,
  description,
  closeTrigger,
} = dialogVariants();

export interface DialogProps
  extends React.ComponentProps<typeof ArkDialog.Root>,
    VariantProps<typeof dialogVariants> {
  className?: string;
}

const DialogRoot = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Root>,
  DialogProps
>(({ className, ...props }, ref) => (
  <ArkDialog.Root className={cn(root(), className)} ref={ref} {...props} />
));
DialogRoot.displayName = "Dialog";

const DialogTrigger = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Trigger>,
  React.ComponentProps<typeof ArkDialog.Trigger>
>(({ className, ...props }, ref) => (
  <ArkDialog.Trigger
    className={cn(trigger(), className)}
    ref={ref}
    {...props}
  />
));
DialogTrigger.displayName = "DialogTrigger";

const DialogBackdrop = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Backdrop>,
  React.ComponentProps<typeof ArkDialog.Backdrop>
>(({ className, ...props }, ref) => (
  <ArkDialog.Backdrop
    className={cn(backdrop(), className)}
    ref={ref}
    {...props}
  />
));
DialogBackdrop.displayName = "DialogBackdrop";

const DialogPositioner = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Positioner>,
  React.ComponentProps<typeof ArkDialog.Positioner>
>(({ className, ...props }, ref) => (
  <ArkDialog.Positioner
    className={cn(positioner(), className)}
    ref={ref}
    {...props}
  />
));
DialogPositioner.displayName = "DialogPositioner";

const DialogContent = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Content>,
  React.ComponentProps<typeof ArkDialog.Content>
>(({ className, children, ...props }, ref) => (
  <Portal>
    <DialogBackdrop />
    <DialogPositioner>
      <ArkDialog.Content
        className={cn(content(), className)}
        ref={ref}
        {...props}
      >
        {children}
      </ArkDialog.Content>
    </DialogPositioner>
  </Portal>
));
DialogContent.displayName = "DialogContent";

const DialogTitle = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Title>,
  React.ComponentProps<typeof ArkDialog.Title>
>(({ className, ...props }, ref) => (
  <ArkDialog.Title className={cn(title(), className)} ref={ref} {...props} />
));
DialogTitle.displayName = "DialogTitle";

const DialogDescription = React.forwardRef<
  React.ElementRef<typeof ArkDialog.Description>,
  React.ComponentProps<typeof ArkDialog.Description>
>(({ className, ...props }, ref) => (
  <ArkDialog.Description
    className={cn(description(), className)}
    ref={ref}
    {...props}
  />
));
DialogDescription.displayName = "DialogDescription";

const DialogCloseTrigger = React.forwardRef<
  React.ElementRef<typeof ArkDialog.CloseTrigger>,
  React.ComponentProps<typeof ArkDialog.CloseTrigger>
>(({ className, ...props }, ref) => (
  <ArkDialog.CloseTrigger
    className={cn(closeTrigger(), className)}
    ref={ref}
    {...props}
  />
));
DialogCloseTrigger.displayName = "DialogCloseTrigger";

export const Dialog = {
  Root: DialogRoot,
  Trigger: DialogTrigger,
  Backdrop: DialogBackdrop,
  Positioner: DialogPositioner,
  Content: DialogContent,
  Title: DialogTitle,
  Description: DialogDescription,
  CloseTrigger: DialogCloseTrigger,
};

// registry/solid/components/dialog.tsx
import { Dialog as ArkDialog, useDialogContext } from "@ark-ui/solid/dialog";
import { ark } from "@ark-ui/solid/factory";
import { XIcon } from "lucide-solid";
import { type ComponentProps, createContext, useContext } from "solid-js";

import { tv, type VariantProps } from "tailwind-variants";
import { cn } from "@/lib/utils";
import { Button } from "@/registry/solid/components/button";
import { ScrollArea } from "@/registry/solid/components/scroll-area";

export const useDialog = useDialogContext;

interface DialogContextProps {
  /**
   * Used internally to show or hide overlay
   *
   * @default true
   */
  modal?: boolean;
}

const DialogContext = createContext({} as DialogContextProps);

export const Dialog = (props: ComponentProps<typeof ArkDialog.Root>) => {
  const {
    modal = true,
    lazyMount = true,
    unmountOnExit = true,
    ...rest
  } = props;

  return (
    <DialogContext.Provider value={{ modal }}>
      <ArkDialog.Root
        lazyMount={lazyMount}
        modal={modal}
        unmountOnExit={unmountOnExit}
        {...rest}
      />
    </DialogContext.Provider>
  );
};

export const DialogTrigger = (
  props: ComponentProps<typeof ArkDialog.Trigger>
) => <ArkDialog.Trigger {...props} />;

export const dialogOverlayVariants = tv({
  base: [
    "fixed inset-0 z-50",
    "bg-black/32 backdrop-blur-xs",
    "duration-200",
    "peer peer-data-[slot=dialog-overlay]:hidden",
    "data-[state=open]:fade-in-0 data-[state=open]:animate-in",
    "data-[state=closed]:fade-out-0 data-[state=closed]:animate-out",
  ],
});

export const DialogOverlay = (
  props: ComponentProps<typeof ArkDialog.Backdrop>
) => {
  const { class: className, ...rest } = props;

  const { modal } = _useDialog();

  if (!modal) {
    return null;
  }

  return (
    <ArkDialog.Backdrop
      class={cn(dialogOverlayVariants(), className)}
      data-slot="dialog-overlay"
      {...rest}
    />
  );
};

export const DialogPositioner = (
  props: ComponentProps<typeof ArkDialog.Positioner>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkDialog.Positioner
      class={cn(
        "fixed inset-0 z-50",
        "h-svh w-screen",
        "grid grid-rows-[1fr_auto_3fr] justify-items-center",
        "p-4",
        className
      )}
      data-slot="dialog-positioner"
      {...rest}
    />
  );
};

export const dialogContentVariants = tv({
  base: [
    "[--space:--spacing(6)]",
    "z-[calc(50+var(--layer-index,0))]",
    "relative",
    "row-start-2",
    "max-h-full min-h-0 w-full min-w-0",
    "flex flex-col",
    "bg-popover",
    "text-popover-foreground",
    "rounded-2xl border shadow-lg/5",
    "outline-none",
    "-translate-y-[calc(1.25rem*var(--nested-layer-count))]",
    "transition-[scale,opacity,translate] duration-200 ease-in-out will-change-transform",
    "data-[nested=dialog]:data-[state=closed]:slide-in-from-bottom-10 data-[nested=dialog]:data-[state=open]:slide-in-from-bottom-10 data-[has-nested=dialog]:origin-top",
    "scale-[calc(1-0.1*var(--nested-layer-count))] opacity-[calc(1-0.1*var(--nested-layer-count))]",
    "data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-[98%] data-[state=closed]:animate-out",
    "data-[state=open]:fade-in-0 data-[state=open]:zoom-in-[98%] data-[state=open]:animate-in",
  ],
  variants: {
    size: {
      sm: ["max-w-md"],
      md: ["max-w-lg"],
      lg: ["max-w-xl"],
      xl: ["max-w-2xl"],
      "2xl": ["max-w-3xl"],
      "3xl": ["max-w-4xl"],
      "4xl": ["max-w-5xl"],
      "5xl": ["max-w-6xl"],
      "6xl": ["max-w-7xl"],
      fullscreen: ["size-full"],
    },
    bottomStickOnMobile: {
      true: [
        "max-sm:max-w-none",
        "max-sm:rounded-none max-sm:rounded-t-2xl max-sm:border-x-0 max-sm:border-t max-sm:border-b-0",
        "max-sm:opacity-[calc(1-min(var(--nested-dialogs),1))]",
        "max-sm:data-[state=closed]:slide-out-to-bottom-5 max-sm:data-[state=open]:slide-in-from-bottom-5",
        "max-sm:data-[state=closed]:zoom-out-100 max-sm:data-[state=open]:zoom-in-100",
      ],
    },
  },
  defaultVariants: {
    size: "md",
  },
});

interface DialogContentProps
  extends ComponentProps<typeof ArkDialog.Content>,
    VariantProps<typeof dialogContentVariants> {
  /**
   * Stick the dialog to the bottom of the screen on mobile
   *
   * @default true
   */
  bottomStickOnMobile?: boolean;
  /**
   * Show close button at the top right corner
   *
   * @default true
   */
  showCloseButton?: boolean;
}

export const DialogContent = (props: DialogContentProps) => {
  const {
    showCloseButton = true,
    bottomStickOnMobile = true,
    size = "md",
    class: className,
    children,
    ...rest
  } = props;

  return (
    <>
      <DialogOverlay />

      <DialogPositioner
        class={cn(
          bottomStickOnMobile &&
            "max-sm:grid-rows-[1fr_auto] max-sm:p-0 max-sm:pt-12"
        )}
      >
        <ArkDialog.Content
          class={cn(
            dialogContentVariants({ size, bottomStickOnMobile }),
            className
          )}
          data-slot="dialog-content"
          {...rest}
        >
          {children}

          {!!showCloseButton && (
            <DialogClose asChild>
              <Button
                aria-label="Close"
                class="absolute inset-e-2 top-2 opacity-64 hover:opacity-100"
                size="icon-sm"
                variant="ghost"
              >
                <XIcon />
              </Button>
            </DialogClose>
          )}
        </ArkDialog.Content>
      </DialogPositioner>
    </>
  );
};

interface DialogBodyProps extends ComponentProps<typeof ark.div> {
  /**
   * Add a fade effect to the scroll area
   *
   * @default false
   */
  scrollFade?: boolean;
}

export const DialogBody = (props: DialogBodyProps) => {
  const { scrollFade = false, className, ...rest } = props;

  return (
    <ScrollArea scrollFade={scrollFade}>
      <ark.div
        class={cn(
          "flex-1",
          "p-(--space)",
          "overflow-auto",
          "in-[[data-slot=dialog-content]:has([data-slot=dialog-header])]:pt-0",
          "in-[[data-slot=dialog-content]:has([data-slot=dialog-footer]:not(.border-t))]:pb-1",
          className
        )}
        data-slot="dialog-body"
        {...rest}
      />
    </ScrollArea>
  );
};

interface DialogHeaderProps extends ComponentProps<typeof ark.div> {
  /**
   * The description of the dialog
   */
  description?: string;
  /**
   * The title of the dialog
   */
  title?: string;
}

export const DialogHeader = (props: DialogHeaderProps) => {
  const { class: className, title, description, children, ...rest } = props;

  return (
    <ark.div
      class={cn(
        "flex flex-col gap-2 p-(--space) in-[[data-slot=dialog-content]:has([data-slot=dialog-body])]:pb-3",
        className
      )}
      data-slot="dialog-header"
      {...rest}
    >
      {!!title && <DialogTitle>{title}</DialogTitle>}

      {!!description && <DialogDescription>{description}</DialogDescription>}

      {!title && typeof children === "string" ? (
        <DialogTitle>{children}</DialogTitle>
      ) : (
        children
      )}
    </ark.div>
  );
};

export const DialogTitle = (props: ComponentProps<typeof ArkDialog.Title>) => {
  const { class: className, ...rest } = props;

  return (
    <ArkDialog.Title
      class={cn("font-semibold text-lg leading-none", className)}
      data-slot="dialog-title"
      {...rest}
    />
  );
};

export const DialogDescription = (
  props: ComponentProps<typeof ArkDialog.Description>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkDialog.Description
      class={cn("text-muted-foreground text-sm", className)}
      data-slot="dialog-description"
      {...rest}
    />
  );
};

export const DialogClose = (
  props: ComponentProps<typeof ArkDialog.CloseTrigger>
) => <ArkDialog.CloseTrigger data-slot="dialog-close-trigger" {...props} />;

export const DialogFooter = (props: ComponentProps<typeof ark.div>) => {
  const { class: className, ...rest } = props;

  return (
    <ark.div
      class={cn(
        "flex flex-col-reverse gap-2 sm:flex-row sm:justify-end",
        "sm:rounded-b-[calc(var(--radius-2xl)-1px)]",
        "px-(--space) py-4",
        "bg-muted/48",
        "border-t",
        className
      )}
      data-slot="dialog-footer"
      {...rest}
    />
  );
};

const _useDialog = () => {
  const context = useContext(DialogContext);

  if (!context) {
    throw new Error("useDialog must be used within a DialogProvider");
  }

  return context;
};
