// components/ui/popover.tsx
import { Popover as ArkPopover } from "@ark-ui/react/popover";
import { cn } from "fumadocs-ui/utils/cn";
import React from "react";
import { tv, type VariantProps } from "tailwind-variants";

const popoverVariants = tv({
  slots: {
    root: "relative",
    trigger: "inline-flex",
    indicator: "ml-1 h-4 w-4",
    positioner: [
      "z-50",
      "data-[state=closed]:animate-out data-[state=open]:animate-in",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      "data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95",
      "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2",
      "data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
    ],
    content: [
      "z-50 w-72 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none",
      "data-[state=closed]:animate-out data-[state=open]:animate-in",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      "data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95",
      "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2",
      "data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
    ],
    title: "font-semibold text-sm",
    description: "text-muted-foreground text-sm",
    closeTrigger: [
      "absolute top-4 right-4 rounded-sm opacity-70 ring-offset-background",
      "transition-opacity hover:opacity-100",
      "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
      "disabled:pointer-events-none",
      "data-[state=open]:bg-accent data-[state=open]:text-muted-foreground",
    ],
    arrow: "fill-popover",
  },
});

const {
  root,
  trigger,
  indicator,
  positioner,
  content,
  title,
  description,
  closeTrigger,
  arrow,
} = popoverVariants();

export interface PopoverProps
  extends React.ComponentProps<typeof ArkPopover.Root>,
    VariantProps<typeof popoverVariants> {}

const PopoverRoot = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Root>,
  PopoverProps
>(({ className, ...props }, ref) => (
  <ArkPopover.Root className={cn(root(), className)} ref={ref} {...props} />
));
PopoverRoot.displayName = "Popover";

const PopoverTrigger = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Trigger>,
  React.ComponentProps<typeof ArkPopover.Trigger>
>(({ className, ...props }, ref) => (
  <ArkPopover.Trigger
    className={cn(trigger(), className)}
    ref={ref}
    {...props}
  />
));
PopoverTrigger.displayName = "PopoverTrigger";

const PopoverIndicator = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Indicator>,
  React.ComponentProps<typeof ArkPopover.Indicator>
>(({ className, ...props }, ref) => (
  <ArkPopover.Indicator
    className={cn(indicator(), className)}
    ref={ref}
    {...props}
  />
));
PopoverIndicator.displayName = "PopoverIndicator";

const PopoverPositioner = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Positioner>,
  React.ComponentProps<typeof ArkPopover.Positioner>
>(({ className, ...props }, ref) => (
  <ArkPopover.Positioner
    className={cn(positioner(), className)}
    ref={ref}
    {...props}
  />
));
PopoverPositioner.displayName = "PopoverPositioner";

const PopoverContent = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Content>,
  React.ComponentProps<typeof ArkPopover.Content>
>(({ className, children, ...props }, ref) => (
  <ArkPopover.Content className={cn(content(), className)} ref={ref} {...props}>
    {children}
  </ArkPopover.Content>
));
PopoverContent.displayName = "PopoverContent";

const PopoverTitle = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Title>,
  React.ComponentProps<typeof ArkPopover.Title>
>(({ className, ...props }, ref) => (
  <ArkPopover.Title className={cn(title(), className)} ref={ref} {...props} />
));
PopoverTitle.displayName = "PopoverTitle";

const PopoverDescription = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Description>,
  React.ComponentProps<typeof ArkPopover.Description>
>(({ className, ...props }, ref) => (
  <ArkPopover.Description
    className={cn(description(), className)}
    ref={ref}
    {...props}
  />
));
PopoverDescription.displayName = "PopoverDescription";

const PopoverCloseTrigger = React.forwardRef<
  React.ElementRef<typeof ArkPopover.CloseTrigger>,
  React.ComponentProps<typeof ArkPopover.CloseTrigger>
>(({ className, ...props }, ref) => (
  <ArkPopover.CloseTrigger
    className={cn(closeTrigger(), className)}
    ref={ref}
    {...props}
  />
));
PopoverCloseTrigger.displayName = "PopoverCloseTrigger";

const PopoverArrow = React.forwardRef<
  React.ElementRef<typeof ArkPopover.Arrow>,
  React.ComponentProps<typeof ArkPopover.Arrow>
>(({ className, ...props }, ref) => (
  <ArkPopover.Arrow className={cn(arrow(), className)} ref={ref} {...props} />
));
PopoverArrow.displayName = "PopoverArrow";

export const Popover = {
  Root: PopoverRoot,
  Trigger: PopoverTrigger,
  Indicator: PopoverIndicator,
  Positioner: PopoverPositioner,
  Content: PopoverContent,
  Title: PopoverTitle,
  Description: PopoverDescription,
  CloseTrigger: PopoverCloseTrigger,
  Arrow: PopoverArrow,
};

// registry/solid/components/popover.tsx
import { ark } from "@ark-ui/solid/factory";
import {
  Popover as ArkPopover,
  usePopoverContext,
} from "@ark-ui/solid/popover";
import { XIcon } from "lucide-solid";
import type { ComponentProps } from "solid-js";
import { cn } from "@/lib/utils";
import { Button } from "@/registry/solid/components/button";
import { ScrollArea } from "@/registry/solid/components/scroll-area";

export const usePopover = usePopoverContext;

export const Popover = (props: ComponentProps<typeof ArkPopover.Root>) => {
  const {
    lazyMount = true,
    unmountOnExit = true,
    modal = true,
    ...rest
  } = props;

  return (
    <ArkPopover.Root
      data-slot="popover"
      lazyMount={lazyMount}
      modal={modal}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};

export const PopoverTrigger = (
  props: ComponentProps<typeof ArkPopover.Trigger>
) => <ArkPopover.Trigger data-slot="popover-trigger" {...props} />;

export const PopoverAnchor = (
  props: ComponentProps<typeof ArkPopover.Anchor>
) => <ArkPopover.Anchor data-slot="popover-anchor" {...props} />;

export const PopoverPositioner = (
  props: ComponentProps<typeof ArkPopover.Positioner>
) => <ArkPopover.Positioner data-slot="popover-positioner" {...props} />;

interface PopoverContentProps
  extends ComponentProps<typeof ArkPopover.Content> {
  /**
   * Show close button at the top right corner
   *
   * @default true
   */
  showCloseButton?: boolean;
}

export const PopoverContent = (props: PopoverContentProps) => {
  const { showCloseButton = false, className, children, ...rest } = props;

  return (
    <>
      <PopoverPositioner>
        <ArkPopover.Content
          class={cn(
            "relative",
            "z-[calc(50+var(--layer-index,0))]",
            "[--space:--spacing(4)]",
            "w-auto min-w-32",
            "flex flex-col",
            "bg-popover",
            "text-popover-foreground",
            "rounded-xl border shadow-lg/5",
            "outline-hidden",
            "origin-(--transform-origin)",
            "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
            "data-[state=closed]:zoom-out-[98%] data-[state=open]:zoom-in-[98%]",
            "data-[state=closed]:animate-out data-[state=open]:animate-in",
            "data-[placement=bottom]:slide-in-from-top-2",
            "data-[placement=left]:slide-in-from-end-2",
            "data-[placement=right]:slide-in-from-start-2",
            "data-[placement=top]:slide-in-from-bottom-2",
            className
          )}
          data-slot="popover-content"
          {...rest}
        >
          {children}

          {!!showCloseButton && (
            <PopoverClose asChild>
              <Button
                aria-label="Close"
                class="absolute inset-e-2 top-2 opacity-64 hover:opacity-100"
                size="icon-sm"
                variant="ghost"
              >
                <XIcon />
              </Button>
            </PopoverClose>
          )}
        </ArkPopover.Content>
      </PopoverPositioner>
    </>
  );
};

interface PopoverHeaderProps extends ComponentProps<typeof ark.div> {
  /**
   * The description of the popover header
   */
  description?: string;
  /**
   * The title of the popover header
   */
  title?: string;
}

export const PopoverHeader = (props: PopoverHeaderProps) => {
  const { title, description, children, className, ...rest } = props;

  return (
    <ark.div
      class={cn(
        "flex flex-col gap-2 p-(--space)",
        "in-[[data-slot=popover-content]:has([data-slot=popover-body])]:pb-3",
        className
      )}
      data-slot="popover-header"
      {...rest}
    >
      {!!title && <PopoverTitle>{title}</PopoverTitle>}
      {!!description && <PopoverDescription>{description}</PopoverDescription>}
      {!title && typeof children === "string" ? (
        <PopoverTitle>{children}</PopoverTitle>
      ) : (
        children
      )}
    </ark.div>
  );
};

export const PopoverTitle = (
  props: ComponentProps<typeof ArkPopover.Title>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkPopover.Title
      class={cn("font-semibold text-base leading-none", className)}
      data-slot="popover-title"
      {...rest}
    />
  );
};

export const PopoverDescription = (
  props: ComponentProps<typeof ArkPopover.Description>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkPopover.Description
      class={cn("text-muted-foreground text-sm", className)}
      data-slot="popover-description"
      {...rest}
    />
  );
};

export const PopoverBody = (props: ComponentProps<typeof ark.div>) => {
  const { class: className, ...rest } = props;

  return (
    <ScrollArea>
      <ark.div
        class={cn(
          "flex-1",
          "p-(--space)",
          "overflow-auto",
          "in-[[data-slot=popover-content]:has([data-slot=popover-header])]:pt-1",
          "in-[[data-slot=popover-content]:has([data-slot=popover-footer]:not(.border-t))]:pb-1",
          className
        )}
        data-slot="popover-body"
        {...rest}
      />
    </ScrollArea>
  );
};

export const PopoverFooter = (props: ComponentProps<typeof ark.div>) => {
  const { class: className, ...rest } = props;

  return (
    <ark.div
      class={cn(
        "flex flex-col-reverse gap-2 sm:flex-row sm:justify-end",
        "sm:rounded-b-[calc(var(--radius-lg)-1px)]",
        "px-(--space) py-4",
        "bg-muted/64",
        "border-t",
        className
      )}
      data-slot="popover-footer"
      {...rest}
    />
  );
};

export const PopoverClose = (
  props: ComponentProps<typeof ArkPopover.CloseTrigger>
) => <ArkPopover.CloseTrigger data-slot="popover-close-trigger" {...props} />;

export const PopoverArrow = (
  props: ComponentProps<typeof ArkPopover.Arrow>
) => {
  const { style, ...rest } = props;

  return (
    <ArkPopover.Arrow
      data-slot="popover-arrow"
      style={
        {
          "--arrow-background": "var(--popover)",
          "--arrow-size": "calc(1.5 * var(--spacing))",
          ...style,
        } as React.CSSProperties
      }
      {...rest}
    >
      <ArkPopover.ArrowTip class="border-s border-t" />
    </ArkPopover.Arrow>
  );
};
