// registry/react/components/presence.tsx
"use client";

import { Presence as ArkPresence } from "@ark-ui/react/presence";
import type React from "react";

export const Presence = (props: React.ComponentProps<typeof ArkPresence>) => {
  const { lazyMount = true, unmountOnExit = true, ...rest } = props;

  return (
    <ArkPresence
      data-slot="presence"
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};

// registry/solid/components/presence.tsx
import { Presence as ArkPresence } from "@ark-ui/solid/presence";
import type { ComponentProps } from "solid-js";

export const Presence = (props: ComponentProps<typeof ArkPresence>) => {
  const { lazyMount = true, unmountOnExit = true, ...rest } = props;

  return (
    <ArkPresence
      data-slot="presence"
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      {...rest}
    />
  );
};
