// components/ui/progress.tsx
import { Progress as ArkProgress } from "@ark-ui/react/progress";
import { cn } from "fumadocs-ui/utils/cn";
import React from "react";
import { tv, type VariantProps } from "tailwind-variants";

const progressVariants = tv({
  slots: {
    root: "relative h-4 w-full overflow-hidden rounded-full bg-secondary",
    track: "h-full w-full bg-secondary",
    range: "h-full bg-primary transition-all",
    label: "font-medium text-foreground text-sm",
    valueText: "text-muted-foreground text-sm",
  },
});

const { root, track, range, label, valueText } = progressVariants();

export interface ProgressProps
  extends React.ComponentProps<typeof ArkProgress.Root>,
    VariantProps<typeof progressVariants> {}

const ProgressRoot = React.forwardRef<
  React.ElementRef<typeof ArkProgress.Root>,
  ProgressProps
>(({ className, ...props }, ref) => (
  <ArkProgress.Root className={cn(root(), className)} ref={ref} {...props} />
));
ProgressRoot.displayName = "Progress";

const ProgressTrack = React.forwardRef<
  React.ElementRef<typeof ArkProgress.Track>,
  React.ComponentProps<typeof ArkProgress.Track>
>(({ className, ...props }, ref) => (
  <ArkProgress.Track className={cn(track(), className)} ref={ref} {...props} />
));
ProgressTrack.displayName = "ProgressTrack";

const ProgressRange = React.forwardRef<
  React.ElementRef<typeof ArkProgress.Range>,
  React.ComponentProps<typeof ArkProgress.Range>
>(({ className, ...props }, ref) => (
  <ArkProgress.Range className={cn(range(), className)} ref={ref} {...props} />
));
ProgressRange.displayName = "ProgressRange";

const ProgressLabel = React.forwardRef<
  React.ElementRef<typeof ArkProgress.Label>,
  React.ComponentProps<typeof ArkProgress.Label>
>(({ className, ...props }, ref) => (
  <ArkProgress.Label className={cn(label(), className)} ref={ref} {...props} />
));
ProgressLabel.displayName = "ProgressLabel";

const ProgressValueText = React.forwardRef<
  React.ElementRef<typeof ArkProgress.ValueText>,
  React.ComponentProps<typeof ArkProgress.ValueText>
>(({ className, ...props }, ref) => (
  <ArkProgress.ValueText
    className={cn(valueText(), className)}
    ref={ref}
    {...props}
  />
));
ProgressValueText.displayName = "ProgressValueText";

export const Progress = {
  Root: ProgressRoot,
  Track: ProgressTrack,
  Range: ProgressRange,
  Label: ProgressLabel,
  ValueText: ProgressValueText,
};

// registry/solid/components/progress.tsx
import {
  Progress as ArkProgress,
  useProgressContext,
} from "@ark-ui/solid/progress";
import type { ComponentProps } from "solid-js";

import { cn } from "@/lib/utils";
import { FieldLabel } from "@/registry/solid/components/field";

export const useProgress = useProgressContext;

interface ProgressProps
  extends Omit<ComponentProps<typeof ArkProgress.Root>, "value"> {
  /**
   * Shows indeterminate progress
   *
   * @default false
   */
  indeterminate?: boolean;
  /**
   * The value of the progress bar
   *
   * @default 0
   */
  value?: number;
}

export const Progress = (props: ProgressProps) => {
  const {
    value,
    orientation = "horizontal",
    indeterminate = false,
    class: className,
    children,
    ...rest
  } = props;

  return (
    <ArkProgress.Root
      class={cn(
        "flex flex-wrap gap-3",
        "data-[orientation=horizontal]:w-full",
        "data-[orientation=vertical]:-scale-y-100",
        className
      )}
      data-slot="progress"
      orientation={orientation}
      value={indeterminate ? null : value}
      {...rest}
    >
      {children}

      <ProgressTrack>
        <ProgressRange />
      </ProgressTrack>
    </ArkProgress.Root>
  );
};

export const ProgressTrack = (
  props: ComponentProps<typeof ArkProgress.Track>
) => {
  return (
    <ArkProgress.Track
      class={cn(
        "bg-input",
        "rounded-full",
        "overflow-x-hidden",
        "data-[orientation=horizontal]:h-2 data-[orientation=horizontal]:w-full",
        "data-[orientation=vertical]:h-full data-[orientation=vertical]:w-2"
      )}
      data-slot="progress-track"
      {...props}
    />
  );
};

export const ProgressRange = (
  props: ComponentProps<typeof ArkProgress.Range>
) => {
  return (
    <ArkProgress.Range
      class={cn(
        "bg-primary",
        "transition-all duration-300 ease-out",
        "data-[orientation=horizontal]:h-full",
        "data-[orientation=vertical]:h-full",
        "data-[state=indeterminate]:w-1/3 data-[state=indeterminate]:animate-indeterminate data-[state=indeterminate]:duration-100"
      )}
      data-slot="progress-range"
      {...props}
    />
  );
};

export const ProgressValue = (
  props: ComponentProps<typeof ArkProgress.ValueText>
) => {
  const { class: className, ...rest } = props;

  return (
    <FieldLabel asChild>
      <ArkProgress.ValueText
        class={cn("ms-auto tabular-nums", className)}
        data-slot="progress-value"
        {...rest}
      />
    </FieldLabel>
  );
};
