// components/ui/radio-group.tsx
import { RadioGroup as ArkRadioGroup } from "@ark-ui/react/radio-group";
import { cn } from "fumadocs-ui/utils/cn";
import React from "react";
import { tv, type VariantProps } from "tailwind-variants";

const radioGroupVariants = tv({
  slots: {
    root: "grid gap-2",
    label:
      "font-medium text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
    indicator: "flex items-center space-x-2",
    item: [
      "flex items-center space-x-2",
      "peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
    ],
    itemControl: [
      "aspect-square h-4 w-4 rounded-full border border-primary text-primary ring-offset-background",
      "focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
      "disabled:cursor-not-allowed disabled:opacity-50",
      "data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground",
    ],
    itemText:
      "font-medium text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
    itemHiddenInput: "sr-only",
  },
});

const { root, label, indicator, item, itemControl, itemText, itemHiddenInput } =
  radioGroupVariants();

export interface RadioGroupProps
  extends React.ComponentProps<typeof ArkRadioGroup.Root>,
    VariantProps<typeof radioGroupVariants> {}

const RadioGroupRoot = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.Root>,
  RadioGroupProps
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.Root className={cn(root(), className)} ref={ref} {...props} />
));
RadioGroupRoot.displayName = "RadioGroup";

const RadioGroupLabel = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.Label>,
  React.ComponentProps<typeof ArkRadioGroup.Label>
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.Label
    className={cn(label(), className)}
    ref={ref}
    {...props}
  />
));
RadioGroupLabel.displayName = "RadioGroupLabel";

const RadioGroupIndicator = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.Indicator>,
  React.ComponentProps<typeof ArkRadioGroup.Indicator>
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.Indicator
    className={cn(indicator(), className)}
    ref={ref}
    {...props}
  />
));
RadioGroupIndicator.displayName = "RadioGroupIndicator";

const RadioGroupItem = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.Item>,
  React.ComponentProps<typeof ArkRadioGroup.Item>
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.Item className={cn(item(), className)} ref={ref} {...props} />
));
RadioGroupItem.displayName = "RadioGroupItem";

const RadioGroupItemControl = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.ItemControl>,
  React.ComponentProps<typeof ArkRadioGroup.ItemControl>
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.ItemControl
    className={cn(itemControl(), className)}
    ref={ref}
    {...props}
  />
));
RadioGroupItemControl.displayName = "RadioGroupItemControl";

const RadioGroupItemText = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.ItemText>,
  React.ComponentProps<typeof ArkRadioGroup.ItemText>
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.ItemText
    className={cn(itemText(), className)}
    ref={ref}
    {...props}
  />
));
RadioGroupItemText.displayName = "RadioGroupItemText";

const RadioGroupItemHiddenInput = React.forwardRef<
  React.ElementRef<typeof ArkRadioGroup.ItemHiddenInput>,
  React.ComponentProps<typeof ArkRadioGroup.ItemHiddenInput>
>(({ className, ...props }, ref) => (
  <ArkRadioGroup.ItemHiddenInput
    className={cn(itemHiddenInput(), className)}
    ref={ref}
    {...props}
  />
));
RadioGroupItemHiddenInput.displayName = "RadioGroupItemHiddenInput";

export const RadioGroup = {
  Root: RadioGroupRoot,
  Label: RadioGroupLabel,
  Indicator: RadioGroupIndicator,
  Item: RadioGroupItem,
  ItemControl: RadioGroupItemControl,
  ItemText: RadioGroupItemText,
  ItemHiddenInput: RadioGroupItemHiddenInput,
};

// registry/solid/components/radio-group.tsx
import {
  RadioGroup as ArkRadioGroup,
  useRadioGroupContext,
} from "@ark-ui/solid/radio-group";
import type { ComponentProps } from "solid-js";

import { cn } from "@/lib/utils";
import { FieldLabel } from "@/registry/solid/components/field";

export const useRadioGroup = useRadioGroupContext;

export const RadioGroup = (
  props: ComponentProps<typeof ArkRadioGroup.Root>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <ArkRadioGroup.Root
      class={cn(
        "flex flex-col gap-3",
        "data-invalid:text-destructive dark:data-invalid:text-destructive-foreground",
        className
      )}
      data-slot="radio-group"
      {...rest}
    >
      {children}
    </ArkRadioGroup.Root>
  );
};

export const RadioGroupItem = (
  props: ComponentProps<typeof ArkRadioGroup.Item>
) => {
  const { tabIndex, className, children, ...rest } = props;

  return (
    <ArkRadioGroup.Item
      class={cn(
        "inline-flex items-center gap-2",
        "data-disabled:opacity-64",
        className
      )}
      data-slot="radio-group-item"
      {...rest}
    >
      <ArkRadioGroup.ItemControl
        class={cn(
          "relative",
          "inline-flex shrink-0 items-center justify-center",
          "size-4",
          "border border-input shadow-xs/5",
          "bg-input/30",
          "rounded-full",
          "before:size-1.5 before:rounded-full",
          "data-focus-visible:border-primary data-focus-visible:ring-[3px] data-focus-visible:ring-ring/32 data-focus-visible:ring-offset-1 data-focus-visible:ring-offset-background",
          "data-focus-visible:data-invalid:border-destructive/64 data-focus-visible:data-invalid:ring-destructive/48",
          "data-invalid:border-destructive data-invalid:text-destructive data-invalid:ring-[3px] data-invalid:ring-destructive/24",
          "dark:data-invalid:border-destructive-foreground dark:data-invalid:text-destructive dark:data-invalid:ring-[3px] dark:data-invalid:ring-destructive-foreground/20",
          "data-[state=checked]:bg-primary data-[state=checked]:before:bg-primary-foreground",
          "data-invalid:data-[state=checked]:bg-transparent data-invalid:data-[state=checked]:before:bg-destructive-foreground"
        )}
        data-slot="radio-group-item-control"
      />

      <RadioGroupText>{children}</RadioGroupText>

      <ArkRadioGroup.ItemHiddenInput tabIndex={tabIndex} />
    </ArkRadioGroup.Item>
  );
};

export const RadioGroupText = (
  props: ComponentProps<typeof ArkRadioGroup.ItemText>
) => {
  const { class: className, children, ...rest } = props;

  return (
    <FieldLabel asChild>
      <ArkRadioGroup.ItemText data-slot="radio-group-item-text" {...rest}>
        {children}
      </ArkRadioGroup.ItemText>
    </FieldLabel>
  );
};

export const RadioGroupLabel = (
  props: ComponentProps<typeof ArkRadioGroup.Label>
) => {
  const { children, ...rest } = props;

  return (
    <FieldLabel asChild>
      <ArkRadioGroup.Label data-slot="radio-group-label" {...rest}>
        {children}
      </ArkRadioGroup.Label>
    </FieldLabel>
  );
};
