// components/thumbs/timer.tsx
import { ThumbCard, type ThumbCardProps } from "./thumb-card";

export const TimerThumb = (props: ThumbCardProps) => (
  <ThumbCard {...props}>
    <div className="inline-flex w-fit items-center justify-center gap-2 rounded-lg border border-input bg-muted px-6 py-4 font-semibold text-muted-foreground text-xl tabular-nums shadow-md/5">
      <div className="h-1.5 w-6 rounded-full bg-muted-foreground/16" />
      <div className="flex flex-col gap-1">
        <div className="size-0.5 rotate-90 rounded-full bg-muted-foreground/32" />
        <div className="size-0.5 rotate-90 rounded-full bg-muted-foreground/32" />
      </div>
      <div className="h-1.5 w-6 rounded-full bg-muted-foreground/16" />
      <div className="flex flex-col gap-1">
        <div className="size-0.5 rotate-90 rounded-full bg-muted-foreground/32" />
        <div className="size-0.5 rotate-90 rounded-full bg-muted-foreground/32" />
      </div>
      <div className="h-1.5 w-6 rounded-full bg-muted-foreground/16" />
      <div className="flex flex-col gap-1">
        <div className="size-0.5 rotate-90 rounded-full bg-muted-foreground/32" />
        <div className="size-0.5 rotate-90 rounded-full bg-muted-foreground/32" />
      </div>
      <div className="h-1.5 w-6 rounded-full bg-muted-foreground/16" />
    </div>
  </ThumbCard>
);

// registry/solid/components/timer.tsx
import {
  Timer as ArkTimer,
  useTimer as useArkTimer,
} from "@ark-ui/solid/timer";
import type { ComponentProps } from "solid-js";

import { cn } from "@/lib/utils";

export const useTimer = useArkTimer;

export const Timer = (props: ComponentProps<typeof ArkTimer.Root>) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTimer.Root
      class={cn("flex flex-col items-start gap-4 text-foreground", className)}
      data-slot="timer"
      {...rest}
    />
  );
};

export const TimerArea = (props: ComponentProps<typeof ArkTimer.Area>) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTimer.Area
      class={cn("flex items-center gap-2", className)}
      data-slot="timer-area"
      {...rest}
    />
  );
};

export const TimerItem = (props: ComponentProps<typeof ArkTimer.Item>) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTimer.Item
      class={cn(
        "min-w-[2ch] text-center font-semibold text-2xl text-foreground tabular-nums",
        className
      )}
      data-slot="timer-item"
      {...rest}
    />
  );
};

export const TimerSeparator = (
  props: ComponentProps<typeof ArkTimer.Separator>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTimer.Separator
      class={cn("font-semibold text-2xl text-muted-foreground", className)}
      data-slot="timer-separator"
      {...rest}
    />
  );
};

export const TimerControl = (
  props: ComponentProps<typeof ArkTimer.Control>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTimer.Control
      class={cn("flex items-center gap-2", className)}
      data-slot="timer-control"
      {...rest}
    />
  );
};

export const TimerActionTrigger = (
  props: ComponentProps<typeof ArkTimer.ActionTrigger>
) => {
  const { class: className, ...rest } = props;

  return (
    <ArkTimer.ActionTrigger
      class={cn(
        "inline-flex cursor-pointer items-center justify-center gap-2 rounded-md border border-input bg-transparent px-4 py-2 font-medium text-foreground text-sm transition-colors",
        "hover:bg-muted",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
        "data-disabled:opacity-64 data-disabled:grayscale",
        "[&_svg]:size-4",
        className
      )}
      data-slot="timer-action"
      {...rest}
    />
  );
};
